version: 0.2
phases:
  pre_build:
    commands:
    - echo "Pré build phase - exemplo baixar dependencia se necessário"
  build:
    commands:
        - echo "Testing and Building"
        - mvn clean test compile war:war
  post_build:
    commands:
      - echo "Movendo os arquivos que serão feitos o upload"
      - mv target/*.war ./ROOT.war
artifacts:
  files:
    - ROOT.war